const SALESFORCE_REQUEST_TIMEOUT_MS = 20_000;
const SALESFORCE_OUTBOX_LEASE_SECONDS = 900;
const SALESFORCE_OUTBOX_DB_TIMEOUT_MS = 15_000;

// GET and PATCH can each use: JWT auth, fallback auth, the initial API request,
// then another JWT + fallback auth pair and one API retry after a 401. Do not
// assume the in-memory token cache is warm when sizing the lease.
const SALESFORCE_OUTBOX_MAX_REQUESTS_PER_OPERATION = 6;
const SALESFORCE_OUTBOX_MAX_REQUESTS_PER_JOB =
  SALESFORCE_OUTBOX_MAX_REQUESTS_PER_OPERATION * 2;
const SALESFORCE_OUTBOX_WORST_REQUEST_PATH_MS =
  SALESFORCE_REQUEST_TIMEOUT_MS * SALESFORCE_OUTBOX_MAX_REQUESTS_PER_JOB;

module.exports = Object.freeze({
  SALESFORCE_REQUEST_TIMEOUT_MS,
  SALESFORCE_OUTBOX_LEASE_SECONDS,
  SALESFORCE_OUTBOX_DB_TIMEOUT_MS,
  SALESFORCE_OUTBOX_MAX_REQUESTS_PER_OPERATION,
  SALESFORCE_OUTBOX_MAX_REQUESTS_PER_JOB,
  SALESFORCE_OUTBOX_WORST_REQUEST_PATH_MS,
});
