-- NEXO Admin Panel — Phase 1 local Supabase SQL artifact
-- Execute manually in Supabase SQL editor when ready. This file must not be run automatically.
-- Backend note: these RLS-enabled admin tables grant service_role only; configure
-- SUPABASE_SERVICE_ROLE_KEY for server-side operations. SUPABASE_ANON_KEY is only
-- a local-development fallback in backend/src/database/db.js.

CREATE TABLE IF NOT EXISTS areas (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL UNIQUE,
  description  TEXT,
  welcome_msg  TEXT,
  active       BOOLEAN DEFAULT true,
  sla_minutes  INT DEFAULT 30,
  created_at   TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE areas ENABLE ROW LEVEL SECURITY;
GRANT ALL PRIVILEGES ON TABLE areas TO service_role;

CREATE TABLE IF NOT EXISTS analysts (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_id      BIGINT REFERENCES dashboard_tokens(id) ON DELETE CASCADE,
  area_id       BIGINT REFERENCES areas(id),
  display_name  TEXT NOT NULL,
  available     BOOLEAN DEFAULT false,
  last_seen     TIMESTAMPTZ,
  created_at    TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE analysts ENABLE ROW LEVEL SECURITY;
GRANT ALL PRIVILEGES ON TABLE analysts TO service_role;

CREATE TABLE IF NOT EXISTS ticket_assignments (
  ticket_id    BIGINT PRIMARY KEY REFERENCES tickets(id) ON DELETE CASCADE,
  analyst_id   BIGINT REFERENCES analysts(id) ON DELETE SET NULL,
  assigned_at  TIMESTAMPTZ DEFAULT now(),
  assigned_by  TEXT DEFAULT 'auto'
);
ALTER TABLE ticket_assignments ENABLE ROW LEVEL SECURITY;
GRANT ALL PRIVILEGES ON TABLE ticket_assignments TO service_role;

CREATE TABLE IF NOT EXISTS bot_flows (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id   BIGINT DEFAULT 1,
  area_id      BIGINT REFERENCES areas(id),
  step_key     TEXT NOT NULL,
  message      TEXT NOT NULL,
  sort_order   INT DEFAULT 0,
  active       BOOLEAN DEFAULT true,
  updated_at   TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE bot_flows ENABLE ROW LEVEL SECURITY;
GRANT ALL PRIVILEGES ON TABLE bot_flows TO service_role;

CREATE TABLE IF NOT EXISTS sf_attachments (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id               BIGINT REFERENCES tickets(id) ON DELETE CASCADE,
  sf_content_document_id  TEXT NOT NULL,
  filename                TEXT,
  mimetype                TEXT,
  size_bytes              INT,
  created_at              TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE sf_attachments ENABLE ROW LEVEL SECURITY;
GRANT ALL PRIVILEGES ON TABLE sf_attachments TO service_role;

CREATE TABLE IF NOT EXISTS audit_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_name  TEXT NOT NULL,
  actor_role  TEXT NOT NULL,
  action      TEXT NOT NULL,
  target_id   TEXT,
  metadata    JSONB,
  created_at  TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
GRANT ALL PRIVILEGES ON TABLE audit_log TO service_role;

ALTER TABLE tickets ADD COLUMN IF NOT EXISTS area_id BIGINT REFERENCES areas(id);
ALTER TABLE bot_sessions ADD COLUMN IF NOT EXISTS flow_version_id BIGINT;
