-- Phase 11 pure read-only catalog diagnostics; returns no application data or function bodies.
begin read only;
set local statement_timeout = '30s';
set local lock_timeout = '3s';
set local search_path = pg_catalog, public;

with expected_functions(signature,result_type,language_name,volatility,security_definer) as (values
 ('phase11_calendar_snapshot(bigint)','jsonb','sql','s',true),('phase11_start_snapshot(bigint,bigint,text,bigint)','bigint','plpgsql','v',true),('phase11_request_fingerprint(jsonb)','text','sql','i',true),('phase11_replay(text,text,text,bigint,jsonb)','jsonb','plpgsql','v',true),('phase11_build_actor_context(text,text,bigint)','bigint','plpgsql','i',true),('phase11_lock_authorized_ticket(bigint,bigint,text,bigint)','tickets','plpgsql','v',true),('phase11_validate_transition(text,text,text)','void','plpgsql','i',false),('phase11_lock_latest_escalation(bigint)','development_escalations','sql','v',true),('phase11_validate_escalation_transition(tickets,development_escalations,text,bigint)','void','plpgsql','v',true),('phase11_persist_escalation(bigint,development_escalations,text,text)','development_escalations','plpgsql','v',true),('phase11_record_escalation_event(development_escalations,jsonb)','bigint','plpgsql','v',true),('phase11_suspend_ticket_for_development(bigint)','void','sql','v',true),('phase11_resume_ticket_after_development(bigint)','void','sql','v',true),('phase11_close_support_clock(bigint,bigint)','void','sql','v',true),('phase11_close_development_clock(bigint,bigint,text)','void','sql','v',true),('phase11_resume_support_clock(bigint,bigint)','void','sql','v',true),('phase11_escalation_response(bigint,bigint,bigint)','jsonb','sql','i',true),('phase11_transfer_sets_new()','trigger','plpgsql','v',false),('transition_conversation(jsonb,text,text,text,bigint)','jsonb','plpgsql','v',true),('claim_conversation(jsonb,text,text,text,bigint)','jsonb','plpgsql','v',true),('update_development_escalation(jsonb,text,text,text,bigint)','jsonb','plpgsql','v',true),('configure_sla_policy(bigint,text,text,text,bigint,integer,integer,text)','jsonb','plpgsql','v',true),('configure_business_calendar(bigint,text,text,jsonb,jsonb,text)','jsonb','plpgsql','v',true)
), expected_constraint_shapes(table_name,constraint_name,constraint_type,key_names,ref_table,ref_key_names,delete_action) as (values
 ('workflow_events','workflow_events_pkey','p',array['id'],null,null,null),('workflow_events','workflow_events_ticket_id_fkey','f',array['ticket_id'],'tickets',array['id'],'r'),('workflow_events','workflow_events_escalation_id_fkey','f',array['escalation_id'],'development_escalations',array['id'],'r'),('workflow_events','workflow_events_actor_id_idempotency_key_key','u',array['actor_id','idempotency_key'],null,null,null),
 ('business_calendars','business_calendars_pkey','p',array['id'],null,null,null),('business_calendars','business_calendars_area_id_fkey','f',array['area_id'],'areas',array['id'],'r'),('business_calendars','business_calendars_area_id_name_version_key','u',array['area_id','name','version'],null,null,null),('business_calendar_windows','business_calendar_windows_pkey','p',array['id'],null,null,null),('business_calendar_windows','business_calendar_windows_calendar_id_fkey','f',array['calendar_id'],'business_calendars',array['id'],'c'),('business_calendar_windows','business_calendar_windows_calendar_id_weekday_starts_at_ends_at','u',array['calendar_id','weekday','starts_at','ends_at'],null,null,null),('business_calendar_exceptions','business_calendar_exceptions_pkey','p',array['id'],null,null,null),('business_calendar_exceptions','business_calendar_exceptions_calendar_id_fkey','f',array['calendar_id'],'business_calendars',array['id'],'c'),('business_calendar_exceptions','business_calendar_exceptions_calendar_id_exception_date_key','u',array['calendar_id','exception_date'],null,null,null),
 ('sla_policies','sla_policies_pkey','p',array['id'],null,null,null),('sla_policies','sla_policies_area_id_fkey','f',array['area_id'],'areas',array['id'],'r'),('sla_policies','sla_policies_calendar_id_fkey','f',array['calendar_id'],'business_calendars',array['id'],'r'),('sla_policies','sla_policies_area_id_priority_clock_type_version_key','u',array['area_id','priority','clock_type','version'],null,null,null),('development_escalations','development_escalations_pkey','p',array['id'],null,null,null),('development_escalations','development_escalations_ticket_id_fkey','f',array['ticket_id'],'tickets',array['id'],'r'),('development_escalations','development_escalations_ticket_id_id_key','u',array['ticket_id','id'],null,null,null),
 ('sla_snapshots','sla_snapshots_pkey','p',array['id'],null,null,null),('sla_snapshots','sla_snapshots_ticket_id_fkey','f',array['ticket_id'],'tickets',array['id'],'r'),('sla_snapshots','sla_snapshots_escalation_id_fkey','f',array['escalation_id'],'development_escalations',array['id'],'r'),('sla_snapshots','sla_snapshots_policy_id_fkey','f',array['policy_id'],'sla_policies',array['id'],'r'),('sla_snapshots','sla_snapshots_calendar_id_fkey','f',array['calendar_id'],'business_calendars',array['id'],'r'),('sla_snapshots','sla_snapshots_ticket_id_escalation_id_clock_type_key','u',array['ticket_id','escalation_id','clock_type'],null,null,null),('sla_clock_segments','sla_clock_segments_pkey','p',array['id'],null,null,null),('sla_clock_segments','sla_clock_segments_snapshot_id_fkey','f',array['snapshot_id'],'sla_snapshots',array['id'],'r'),('sla_clock_segments','sla_clock_segments_start_event_id_fkey','f',array['start_event_id'],'workflow_events',array['id'],'r'),('sla_clock_segments','sla_clock_segments_stop_event_id_fkey','f',array['stop_event_id'],'workflow_events',array['id'],'r')
), expected_check_markers(table_name,constraint_name,marker) as (values
 ('business_calendars','business_calendars_timezone_check','nexo:phase11:contract:business_calendars_timezone_check:v2:6d641b7af706ffc80b8bd6ef962d989232c763a175cee241fa20ec5dd6ba99fa'),
 ('business_calendar_windows','business_calendar_windows_weekday_check','nexo:phase11:contract:business_calendar_windows_weekday_check:v2:620aa4e1552bef6a252f827d6746b758b676e494a088d2a12111bc47e9d9c546'),('business_calendar_windows','business_calendar_windows_check','nexo:phase11:contract:business_calendar_windows_check:v2:661021bf4b91e04e8c56ad9c0d5ce20cc7235e2d9d7356bd0e47fc9390200fa4'),
 ('business_calendar_exceptions','business_calendar_exceptions_check','nexo:phase11:contract:business_calendar_exceptions_check:v2:b0061b47e4efad2b348c97a0eea6bf3e7eabb490e5ece48d3162edfb8852c9a5'),
 ('sla_policies','sla_policies_priority_check','nexo:phase11:contract:sla_policies_priority_check:v2:d2bdb5a68104c9136a5742d629c593395cc373cf756e29e3223e100bd8bd2723'),('sla_policies','sla_policies_clock_type_check','nexo:phase11:contract:sla_policies_clock_type_check:v2:6ff5cf1bb7abe6b2ca20cba9f6e919dddfbca4c9be1de8a339e8ce3e37c47619'),('sla_policies','sla_policies_clock_mode_check','nexo:phase11:contract:sla_policies_clock_mode_check:v2:a22244dc831f41dc3821a35616e03a35824565577a1f6ef9dea4e2f1b2d542a9'),('sla_policies','sla_policies_target_minutes_check','nexo:phase11:contract:sla_policies_target_minutes_check:v2:62acd5b3df939f47805f0dbc847fb8056d73f2c4702f5e713a032b754a0ceb4f'),('sla_policies','sla_policies_warning_minutes_check','nexo:phase11:contract:sla_policies_warning_minutes_check:v2:ceb51cb63dba4ac5583e5c0df12d16c5349b4ca25e4ab5e6e71156e5b6b5b607'),('sla_policies','sla_policies_check','nexo:phase11:contract:sla_policies_check:v2:8c2efbdda296dab6effcb6fd1d4bb10e07f818f766f2b95f6062ac76a33ccb4f'),
 ('development_escalations','development_escalations_status_check','nexo:phase11:contract:development_escalations_status_check:v2:cdd48389db888f5dbfb103be24a2a46d67a63c794744c61aa376563405cc87a4'),('sla_snapshots','sla_snapshots_clock_type_check','nexo:phase11:contract:sla_snapshots_clock_type_check:v2:806ff6a2762a99899081e356e146e6d94824d7a2f275cd06b8800af253cd2ae4'),('sla_snapshots','sla_snapshots_clock_mode_check','nexo:phase11:contract:sla_snapshots_clock_mode_check:v2:b97dd8e540a93033e2d41f0a5b901b8c188492d9c8686478756ef5bb36f949fd'),('sla_clock_segments','sla_clock_segments_check','nexo:phase11:contract:sla_clock_segments_check:v2:c6ca24c24236b9ca6953e5796fa061505c3f8a4c28a1ec295e4e42ff448fe92f')
), expected_constraint_names as (
 select table_name,constraint_name from expected_constraint_shapes union select table_name,constraint_name from expected_check_markers
), expected_tables(name) as (values ('business_calendars'),('business_calendar_windows'),('business_calendar_exceptions'),('sla_policies'),('development_escalations'),('workflow_events'),('sla_snapshots'),('sla_clock_segments')),
actual_constraints as (
 select t.relname::text table_name,c.conname::text constraint_name,c.contype::text constraint_type,c.convalidated,obj_description(c.oid,'pg_constraint') marker,
  coalesce((select array_agg(a.attname::text order by k.ord)::text[] from unnest(c.conkey) with ordinality k(attnum,ord) join pg_attribute a on a.attrelid=c.conrelid and a.attnum=k.attnum),array[]::text[]) key_names,
  rt.relname::text ref_table,coalesce((select array_agg(a.attname::text order by k.ord)::text[] from unnest(c.confkey) with ordinality k(attnum,ord) join pg_attribute a on a.attrelid=c.confrelid and a.attnum=k.attnum),array[]::text[]) ref_key_names,c.confdeltype::text delete_action
 from pg_constraint c join pg_class t on t.oid=c.conrelid join pg_namespace n on n.oid=t.relnamespace left join pg_class rt on rt.oid=c.confrelid
 where n.nspname::text='public' and t.relname::text in (select name from expected_tables)
), mismatches as (
 select 'function_contract'::text mismatch_kind,e.signature object_name,jsonb_build_object('expected',jsonb_build_object('result',e.result_type,'language',e.language_name,'volatility',e.volatility,'security_definer',e.security_definer,'owner','postgres|supabase_admin','search_path',array['pg_catalog','public']),'actual',case when p.oid is null then null else jsonb_build_object('result',pg_get_function_result(p.oid),'language',l.lanname,'volatility',p.provolatile::text,'security_definer',p.prosecdef,'owner',r.rolname,'search_path',p.proconfig) end) metadata
 from expected_functions e left join pg_proc p on p.oid=to_regprocedure('public.'||e.signature)::oid left join pg_language l on l.oid=p.prolang left join pg_roles r on r.oid=p.proowner where p.oid is null or pg_get_function_result(p.oid) is distinct from e.result_type or l.lanname::text is distinct from e.language_name or p.provolatile::text is distinct from e.volatility or p.prosecdef is distinct from e.security_definer or p.proconfig is distinct from array['search_path=pg_catalog, public']::text[] or r.rolname::text is null or r.rolname::text not in ('postgres','supabase_admin')
 union all select 'expected_constraint_missing_or_shape',e.table_name||'.'||e.constraint_name,jsonb_build_object('expected',to_jsonb(e),'actual',to_jsonb(a)) from expected_constraint_shapes e left join actual_constraints a using(table_name,constraint_name) where a.constraint_name is null or a.constraint_type is distinct from e.constraint_type or a.key_names is distinct from e.key_names or a.convalidated is distinct from true or (e.constraint_type='f' and (a.ref_table is distinct from e.ref_table or a.ref_key_names is distinct from e.ref_key_names or a.delete_action is distinct from e.delete_action))
 union all select 'expected_check_missing_or_marker',e.table_name||'.'||e.constraint_name,jsonb_build_object('expected_marker',e.marker,'actual_type',a.constraint_type,'actual_validated',a.convalidated,'actual_marker',a.marker) from expected_check_markers e left join actual_constraints a using(table_name,constraint_name) where a.constraint_name is null or a.constraint_type is distinct from 'c' or a.convalidated is distinct from true or a.marker is distinct from e.marker
 union all select 'unexpected_constraint',a.table_name||'.'||a.constraint_name,jsonb_build_object('actual',to_jsonb(a)) from actual_constraints a where not exists(select 1 from expected_constraint_names e where e.table_name=a.table_name and e.constraint_name=a.constraint_name)
)
select mismatch_kind,object_name,metadata from mismatches order by mismatch_kind,object_name;
rollback;
