-- NEXO Bot Flow Studio — Phase 8 persisted design drafts
-- Apply manually in Supabase SQL editor. The application never runs this file.
-- Idempotent: safe to execute again after a successful application.

CREATE TABLE IF NOT EXISTS bot_flow_studio_layouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version_id INTEGER NOT NULL CHECK (version_id > 0),
  area_id BIGINT NULL REFERENCES areas(id) ON DELETE CASCADE,
  layout JSONB NOT NULL DEFAULT '{"schema_version":1,"nodes":[],"edges":[]}'::jsonb,
  revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by TEXT NOT NULL CHECK (char_length(updated_by) BETWEEN 1 AND 160),
  CONSTRAINT bot_flow_studio_layout_object CHECK (jsonb_typeof(layout) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS bot_flow_studio_layouts_effective_identity_uidx
  ON bot_flow_studio_layouts (version_id, COALESCE(area_id, 0));
CREATE INDEX IF NOT EXISTS bot_flow_studio_layouts_updated_at_idx
  ON bot_flow_studio_layouts (updated_at DESC);

ALTER TABLE bot_flow_studio_layouts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE bot_flow_studio_layouts FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE ON TABLE bot_flow_studio_layouts TO service_role;

REVOKE ALL ON SEQUENCE bot_flow_studio_layouts_id_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE bot_flow_studio_layouts_id_seq TO service_role;

CREATE OR REPLACE FUNCTION put_bot_flow_studio_layout(
  p_version_id INTEGER,
  p_area_id BIGINT,
  p_layout JSONB,
  p_expected_revision INTEGER,
  p_updated_by TEXT
) RETURNS SETOF bot_flow_studio_layouts
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  current_row bot_flow_studio_layouts%ROWTYPE;
BEGIN
  -- FOR UPDATE cannot lock an absent row. Serialize every scope, including its
  -- first insert, so concurrent revision-0 writers produce one row and one
  -- empty RPC result (the route's optimistic-conflict signal).
  PERFORM pg_advisory_xact_lock(
    hashtextextended(
      p_version_id::TEXT || ':' || COALESCE(p_area_id::TEXT, 'global'),
      0
    )
  );

  SELECT * INTO current_row
  FROM bot_flow_studio_layouts
  WHERE version_id = p_version_id AND COALESCE(area_id, 0) = COALESCE(p_area_id, 0)
  FOR UPDATE;

  IF FOUND THEN
    IF current_row.revision <> p_expected_revision THEN RETURN; END IF;
    RETURN QUERY UPDATE bot_flow_studio_layouts
      SET layout = p_layout, revision = revision + 1, updated_at = NOW(), updated_by = p_updated_by
      WHERE id = current_row.id
      RETURNING *;
  ELSE
    IF p_expected_revision <> 0 THEN RETURN; END IF;
    RETURN QUERY INSERT INTO bot_flow_studio_layouts(version_id, area_id, layout, revision, updated_by)
      VALUES (p_version_id, p_area_id, p_layout, 1, p_updated_by)
      RETURNING *;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION put_bot_flow_studio_layout(INTEGER, BIGINT, JSONB, INTEGER, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION put_bot_flow_studio_layout(INTEGER, BIGINT, JSONB, INTEGER, TEXT) TO service_role;
