-- NEXO Phase 6 — Salesforce Outbox foundation.
-- Artifact only: apply manually in Supabase when promoting this slice.
-- This slice intentionally creates storage/status visibility only; no worker is
-- started and no Salesforce calls are made by this SQL artifact.
-- Supported operations are intentionally limited to case_create and case_close:
-- both have one safe idempotency slot per ticket/case. Add case_update only
-- after defining a stable fingerprint for each distinct update payload.

CREATE TABLE IF NOT EXISTS salesforce_outbox (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id        BIGINT NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  sf_case_id       TEXT,
  operation        TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending',
  payload          JSONB NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key  TEXT NOT NULL UNIQUE,
  attempts         INT NOT NULL DEFAULT 0,
  last_error       TEXT,
  next_attempt_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at     TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT salesforce_outbox_status_chk CHECK (
    status IN ('pending', 'retrying', 'failed', 'synced')
  ),
  CONSTRAINT salesforce_outbox_operation_chk CHECK (
    operation IN ('case_create', 'case_close')
  )
);

ALTER TABLE salesforce_outbox ENABLE ROW LEVEL SECURITY;
GRANT ALL PRIVILEGES ON TABLE salesforce_outbox TO service_role;
GRANT USAGE, SELECT ON SEQUENCE salesforce_outbox_id_seq TO service_role;

CREATE INDEX IF NOT EXISTS salesforce_outbox_status_next_attempt_idx
  ON salesforce_outbox (status, next_attempt_at ASC, created_at ASC);

CREATE INDEX IF NOT EXISTS salesforce_outbox_ticket_created_idx
  ON salesforce_outbox (ticket_id, created_at DESC);

CREATE INDEX IF NOT EXISTS salesforce_outbox_case_created_idx
  ON salesforce_outbox (sf_case_id, created_at DESC)
  WHERE sf_case_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS salesforce_outbox_operation_status_idx
  ON salesforce_outbox (operation, status, created_at DESC);
