-- Phase 11 pure read-only catalog postflight; every row must PASS.
begin read only;
set local statement_timeout = '30s';
set local lock_timeout = '3s';
set local search_path = pg_catalog, public;

with expected_tables(name) as (values
 ('business_calendars'),('business_calendar_windows'),('business_calendar_exceptions'),('sla_policies'),
 ('development_escalations'),('workflow_events'),('sla_snapshots'),('sla_clock_segments')
), tables as (select name,to_regclass('public.'||name) oid from expected_tables),
sequences as (
 select distinct seq.relname name,seq.oid,seq.relowner from tables e join pg_class t on t.oid=e.oid
 join pg_depend d on d.refobjid=t.oid and d.refobjsubid>0 and d.deptype in ('a','i')
 join pg_class seq on seq.oid=d.objid and seq.relkind='S'
), expected_columns(table_name,column_name,data_type,nullable,default_expr,identity_kind) as (values
 ('tickets','conversation_state','text',false,'''new''::text',''),('tickets','waiting_reason','text',true,null,''),
 ('tickets','workflow_revision','bigint',false,'0',''),('tickets','priority_normalized','text',true,null,''),
 ('business_calendars','id','bigint',false,null,'d'),('business_calendars','area_id','bigint',true,null,''),('business_calendars','name','text',false,null,''),('business_calendars','timezone','text',false,'''America/Bogota''::text',''),('business_calendars','version','bigint',false,'1',''),('business_calendars','active','boolean',false,'true',''),('business_calendars','created_at','timestamp with time zone',false,'now()',''),('business_calendars','updated_at','timestamp with time zone',false,'now()',''),
 ('business_calendar_windows','id','bigint',false,null,'d'),('business_calendar_windows','calendar_id','bigint',false,null,''),('business_calendar_windows','weekday','smallint',false,null,''),('business_calendar_windows','starts_at','time without time zone',false,null,''),('business_calendar_windows','ends_at','time without time zone',false,null,''),
 ('business_calendar_exceptions','id','bigint',false,null,'d'),('business_calendar_exceptions','calendar_id','bigint',false,null,''),('business_calendar_exceptions','exception_date','date',false,null,''),('business_calendar_exceptions','closed','boolean',false,'true',''),('business_calendar_exceptions','windows','jsonb',true,null,''),
 ('sla_policies','id','bigint',false,null,'d'),('sla_policies','area_id','bigint',false,null,''),('sla_policies','priority','text',false,null,''),('sla_policies','clock_type','text',false,null,''),('sla_policies','clock_mode','text',false,'''business_hours''::text',''),('sla_policies','calendar_id','bigint',true,null,''),('sla_policies','target_minutes','integer',false,null,''),('sla_policies','warning_minutes','integer',false,null,''),('sla_policies','version','bigint',false,'1',''),('sla_policies','active','boolean',false,'true',''),('sla_policies','created_at','timestamp with time zone',false,'now()',''),('sla_policies','created_by','text',false,null,''),
 ('development_escalations','id','bigint',false,null,'d'),('development_escalations','ticket_id','bigint',false,null,''),('development_escalations','status','text',false,null,''),('development_escalations','revision','bigint',false,'0',''),('development_escalations','requested_by','text',false,null,''),('development_escalations','requested_at','timestamp with time zone',false,'now()',''),('development_escalations','updated_at','timestamp with time zone',false,'now()',''),('development_escalations','resolved_at','timestamp with time zone',true,null,''),
 ('workflow_events','id','bigint',false,null,'d'),('workflow_events','ticket_id','bigint',false,null,''),('workflow_events','escalation_id','bigint',true,null,''),('workflow_events','event_type','text',false,null,''),('workflow_events','from_value','text',true,null,''),('workflow_events','to_value','text',true,null,''),('workflow_events','actor_id','text',false,null,''),('workflow_events','actor_name','text',false,null,''),('workflow_events','actor_role','text',false,null,''),('workflow_events','idempotency_key','text',false,null,''),('workflow_events','request_fingerprint','text',false,null,''),('workflow_events','request_payload','jsonb',false,null,''),('workflow_events','metadata','jsonb',false,'''{}''::jsonb',''),('workflow_events','created_at','timestamp with time zone',false,'now()',''),
 ('sla_snapshots','id','bigint',false,null,'d'),('sla_snapshots','ticket_id','bigint',false,null,''),('sla_snapshots','escalation_id','bigint',true,null,''),('sla_snapshots','clock_type','text',false,null,''),('sla_snapshots','policy_id','bigint',false,null,''),('sla_snapshots','policy_version','bigint',false,null,''),('sla_snapshots','calendar_id','bigint',true,null,''),('sla_snapshots','calendar_version','bigint',true,null,''),('sla_snapshots','clock_mode','text',false,null,''),('sla_snapshots','timezone','text',false,null,''),('sla_snapshots','target_minutes','integer',false,null,''),('sla_snapshots','warning_minutes','integer',false,null,''),('sla_snapshots','calendar_snapshot','jsonb',false,null,''),('sla_snapshots','created_at','timestamp with time zone',false,'now()',''),
 ('sla_clock_segments','id','bigint',false,null,'d'),('sla_clock_segments','snapshot_id','bigint',false,null,''),('sla_clock_segments','started_at','timestamp with time zone',false,null,''),('sla_clock_segments','stopped_at','timestamp with time zone',true,null,''),('sla_clock_segments','start_event_id','bigint',false,null,''),('sla_clock_segments','stop_event_id','bigint',true,null,''),('sla_clock_segments','stop_reason','text',true,null,'')
), expected_constraints(table_name,constraint_name,definition) as (values
 ('tickets','tickets_conversation_state_check',E'CHECK (conversation_state = ANY (ARRAY[\'new\'::text, \'in_progress\'::text, \'waiting\'::text, \'closed\'::text]))'),
 ('tickets','tickets_waiting_reason_check',E'CHECK (conversation_state = \'waiting\'::text AND waiting_reason = ANY (ARRAY[\'customer_response\'::text, \'internal_information\'::text, \'development_escalation\'::text, \'special_situation\'::text]) OR conversation_state <> \'waiting\'::text AND waiting_reason IS NULL)'),
 ('tickets','tickets_priority_normalized_check',E'CHECK (priority_normalized IS NULL OR priority_normalized = ANY (ARRAY[\'critical\'::text, \'high\'::text, \'medium\'::text, \'low\'::text]))'),
 ('workflow_events','workflow_events_pkey','PRIMARY KEY (id)'),('workflow_events','workflow_events_ticket_id_fkey','FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE RESTRICT'),('workflow_events','workflow_events_escalation_id_fkey','FOREIGN KEY (escalation_id) REFERENCES development_escalations(id) ON DELETE RESTRICT'),('workflow_events','workflow_events_actor_id_idempotency_key_key','UNIQUE (actor_id, idempotency_key)'),
 ('business_calendars','business_calendars_pkey','PRIMARY KEY (id)'),('business_calendars','business_calendars_area_id_fkey','FOREIGN KEY (area_id) REFERENCES areas(id) ON DELETE RESTRICT'),('business_calendars','business_calendars_area_id_name_version_key','UNIQUE (area_id, name, version)'),('business_calendars','business_calendars_timezone_check','CHECK (length(timezone) >= 1 AND length(timezone) <= 100)'),
 ('business_calendar_windows','business_calendar_windows_pkey','PRIMARY KEY (id)'),('business_calendar_windows','business_calendar_windows_calendar_id_fkey','FOREIGN KEY (calendar_id) REFERENCES business_calendars(id) ON DELETE CASCADE'),('business_calendar_windows','business_calendar_windows_calendar_id_weekday_starts_at_ends_at','UNIQUE (calendar_id, weekday, starts_at, ends_at)'),('business_calendar_windows','business_calendar_windows_weekday_check','CHECK (weekday >= 0 AND weekday <= 6)'),('business_calendar_windows','business_calendar_windows_check','CHECK (starts_at <> ends_at)'),
 ('business_calendar_exceptions','business_calendar_exceptions_pkey','PRIMARY KEY (id)'),('business_calendar_exceptions','business_calendar_exceptions_calendar_id_fkey','FOREIGN KEY (calendar_id) REFERENCES business_calendars(id) ON DELETE CASCADE'),('business_calendar_exceptions','business_calendar_exceptions_calendar_id_exception_date_key','UNIQUE (calendar_id, exception_date)'),('business_calendar_exceptions','business_calendar_exceptions_check',E'CHECK (closed AND windows IS NULL OR NOT closed AND jsonb_typeof(windows) = \'array\'::text)'),
 ('sla_policies','sla_policies_pkey','PRIMARY KEY (id)'),('sla_policies','sla_policies_area_id_fkey','FOREIGN KEY (area_id) REFERENCES areas(id) ON DELETE RESTRICT'),('sla_policies','sla_policies_calendar_id_fkey','FOREIGN KEY (calendar_id) REFERENCES business_calendars(id) ON DELETE RESTRICT'),('sla_policies','sla_policies_area_id_priority_clock_type_version_key','UNIQUE (area_id, priority, clock_type, version)'),('sla_policies','sla_policies_priority_check',E'CHECK (priority = ANY (ARRAY[\'critical\'::text, \'high\'::text, \'medium\'::text, \'low\'::text]))'),('sla_policies','sla_policies_clock_type_check',E'CHECK (clock_type = ANY (ARRAY[\'support\'::text, \'development\'::text]))'),('sla_policies','sla_policies_clock_mode_check',E'CHECK (clock_mode = ANY (ARRAY[\'business_hours\'::text, \'24x7\'::text]))'),('sla_policies','sla_policies_target_minutes_check','CHECK (target_minutes > 0)'),('sla_policies','sla_policies_warning_minutes_check','CHECK (warning_minutes >= 0 AND warning_minutes < target_minutes)'),('sla_policies','sla_policies_check',E'CHECK (clock_mode = \'24x7\'::text OR calendar_id IS NOT NULL)'),
 ('development_escalations','development_escalations_pkey','PRIMARY KEY (id)'),('development_escalations','development_escalations_ticket_id_fkey','FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE RESTRICT'),('development_escalations','development_escalations_ticket_id_id_key','UNIQUE (ticket_id, id)'),('development_escalations','development_escalations_status_check',E'CHECK (status = ANY (ARRAY[\'requested\'::text, \'in_progress\'::text, \'resolved\'::text, \'cancelled\'::text]))'),
 ('sla_snapshots','sla_snapshots_pkey','PRIMARY KEY (id)'),('sla_snapshots','sla_snapshots_ticket_id_fkey','FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE RESTRICT'),('sla_snapshots','sla_snapshots_escalation_id_fkey','FOREIGN KEY (escalation_id) REFERENCES development_escalations(id) ON DELETE RESTRICT'),('sla_snapshots','sla_snapshots_policy_id_fkey','FOREIGN KEY (policy_id) REFERENCES sla_policies(id) ON DELETE RESTRICT'),('sla_snapshots','sla_snapshots_calendar_id_fkey','FOREIGN KEY (calendar_id) REFERENCES business_calendars(id) ON DELETE RESTRICT'),('sla_snapshots','sla_snapshots_ticket_id_escalation_id_clock_type_key','UNIQUE (ticket_id, escalation_id, clock_type)'),('sla_snapshots','sla_snapshots_clock_type_check',E'CHECK (clock_type = ANY (ARRAY[\'support\'::text, \'development\'::text]))'),('sla_snapshots','sla_snapshots_clock_mode_check',E'CHECK (clock_mode = ANY (ARRAY[\'business_hours\'::text, \'24x7\'::text]))'),
 ('sla_clock_segments','sla_clock_segments_pkey','PRIMARY KEY (id)'),('sla_clock_segments','sla_clock_segments_snapshot_id_fkey','FOREIGN KEY (snapshot_id) REFERENCES sla_snapshots(id) ON DELETE RESTRICT'),('sla_clock_segments','sla_clock_segments_start_event_id_fkey','FOREIGN KEY (start_event_id) REFERENCES workflow_events(id) ON DELETE RESTRICT'),('sla_clock_segments','sla_clock_segments_stop_event_id_fkey','FOREIGN KEY (stop_event_id) REFERENCES workflow_events(id) ON DELETE RESTRICT'),('sla_clock_segments','sla_clock_segments_check','CHECK (stopped_at IS NULL OR stopped_at >= started_at)')
), expected_constraint_shapes(table_name,constraint_name,constraint_type,key_names,ref_table,ref_key_names,delete_action) as (values
 ('workflow_events','workflow_events_pkey','p',array['id'],null,null,null),('workflow_events','workflow_events_ticket_id_fkey','f',array['ticket_id'],'tickets',array['id'],'r'),('workflow_events','workflow_events_escalation_id_fkey','f',array['escalation_id'],'development_escalations',array['id'],'r'),('workflow_events','workflow_events_actor_id_idempotency_key_key','u',array['actor_id','idempotency_key'],null,null,null),
 ('business_calendars','business_calendars_pkey','p',array['id'],null,null,null),('business_calendars','business_calendars_area_id_fkey','f',array['area_id'],'areas',array['id'],'r'),('business_calendars','business_calendars_area_id_name_version_key','u',array['area_id','name','version'],null,null,null),
 ('business_calendar_windows','business_calendar_windows_pkey','p',array['id'],null,null,null),('business_calendar_windows','business_calendar_windows_calendar_id_fkey','f',array['calendar_id'],'business_calendars',array['id'],'c'),('business_calendar_windows','business_calendar_windows_calendar_id_weekday_starts_at_ends_at','u',array['calendar_id','weekday','starts_at','ends_at'],null,null,null),
 ('business_calendar_exceptions','business_calendar_exceptions_pkey','p',array['id'],null,null,null),('business_calendar_exceptions','business_calendar_exceptions_calendar_id_fkey','f',array['calendar_id'],'business_calendars',array['id'],'c'),('business_calendar_exceptions','business_calendar_exceptions_calendar_id_exception_date_key','u',array['calendar_id','exception_date'],null,null,null),
 ('sla_policies','sla_policies_pkey','p',array['id'],null,null,null),('sla_policies','sla_policies_area_id_fkey','f',array['area_id'],'areas',array['id'],'r'),('sla_policies','sla_policies_calendar_id_fkey','f',array['calendar_id'],'business_calendars',array['id'],'r'),('sla_policies','sla_policies_area_id_priority_clock_type_version_key','u',array['area_id','priority','clock_type','version'],null,null,null),
 ('development_escalations','development_escalations_pkey','p',array['id'],null,null,null),('development_escalations','development_escalations_ticket_id_fkey','f',array['ticket_id'],'tickets',array['id'],'r'),('development_escalations','development_escalations_ticket_id_id_key','u',array['ticket_id','id'],null,null,null),
 ('sla_snapshots','sla_snapshots_pkey','p',array['id'],null,null,null),('sla_snapshots','sla_snapshots_ticket_id_fkey','f',array['ticket_id'],'tickets',array['id'],'r'),('sla_snapshots','sla_snapshots_escalation_id_fkey','f',array['escalation_id'],'development_escalations',array['id'],'r'),('sla_snapshots','sla_snapshots_policy_id_fkey','f',array['policy_id'],'sla_policies',array['id'],'r'),('sla_snapshots','sla_snapshots_calendar_id_fkey','f',array['calendar_id'],'business_calendars',array['id'],'r'),('sla_snapshots','sla_snapshots_ticket_id_escalation_id_clock_type_key','u',array['ticket_id','escalation_id','clock_type'],null,null,null),
 ('sla_clock_segments','sla_clock_segments_pkey','p',array['id'],null,null,null),('sla_clock_segments','sla_clock_segments_snapshot_id_fkey','f',array['snapshot_id'],'sla_snapshots',array['id'],'r'),('sla_clock_segments','sla_clock_segments_start_event_id_fkey','f',array['start_event_id'],'workflow_events',array['id'],'r'),('sla_clock_segments','sla_clock_segments_stop_event_id_fkey','f',array['stop_event_id'],'workflow_events',array['id'],'r')
), expected_indexes(table_name,index_name,is_unique,key_names,predicate) as (values
 ('sla_policies','sla_policies_one_active_idx',true,array['area_id','priority','clock_type'],E'active'),
 ('development_escalations','development_escalations_active_ticket_idx',true,array['ticket_id'],E'(status = ANY (ARRAY[\'requested\'::text, \'in_progress\'::text]))'),
 ('sla_snapshots','sla_snapshots_support_once_idx',true,array['ticket_id','clock_type'],E'(escalation_id IS NULL)'),
 ('sla_snapshots','sla_snapshots_escalation_once_idx',true,array['escalation_id','clock_type'],E'(escalation_id IS NOT NULL)'),
 ('sla_clock_segments','sla_clock_segments_open_idx',true,array['snapshot_id'],E'(stopped_at IS NULL)')
), expected_markers(object_kind,table_name,object_name,marker) as (values
 ('constraint','tickets','tickets_conversation_state_check','nexo:phase11:contract:tickets_conversation_state_check:v2:3e839e26a3363307feff4c79852cd715edc1619a11322d87b769d2e06b2b4534'),
 ('constraint','tickets','tickets_waiting_reason_check','nexo:phase11:contract:tickets_waiting_reason_check:v2:c46be18ae0af91fd9a20b99cbf1cf77788a4785750b47b933bc7a5521fd0953c'),
 ('constraint','tickets','tickets_priority_normalized_check','nexo:phase11:contract:tickets_priority_normalized_check:v2:86dc1f91c271d4438e41e83d0411c51ef9205b46e82610bc2c8b173986cf41a8'),
 ('constraint','business_calendars','business_calendars_timezone_check','nexo:phase11:contract:business_calendars_timezone_check:v2:6d641b7af706ffc80b8bd6ef962d989232c763a175cee241fa20ec5dd6ba99fa'),
 ('constraint','business_calendar_windows','business_calendar_windows_weekday_check','nexo:phase11:contract:business_calendar_windows_weekday_check:v2:620aa4e1552bef6a252f827d6746b758b676e494a088d2a12111bc47e9d9c546'),
 ('constraint','business_calendar_windows','business_calendar_windows_check','nexo:phase11:contract:business_calendar_windows_check:v2:661021bf4b91e04e8c56ad9c0d5ce20cc7235e2d9d7356bd0e47fc9390200fa4'),
 ('constraint','business_calendar_exceptions','business_calendar_exceptions_check','nexo:phase11:contract:business_calendar_exceptions_check:v2:b0061b47e4efad2b348c97a0eea6bf3e7eabb490e5ece48d3162edfb8852c9a5'),
 ('constraint','sla_policies','sla_policies_priority_check','nexo:phase11:contract:sla_policies_priority_check:v2:d2bdb5a68104c9136a5742d629c593395cc373cf756e29e3223e100bd8bd2723'),
 ('constraint','sla_policies','sla_policies_clock_type_check','nexo:phase11:contract:sla_policies_clock_type_check:v2:6ff5cf1bb7abe6b2ca20cba9f6e919dddfbca4c9be1de8a339e8ce3e37c47619'),
 ('constraint','sla_policies','sla_policies_clock_mode_check','nexo:phase11:contract:sla_policies_clock_mode_check:v2:a22244dc831f41dc3821a35616e03a35824565577a1f6ef9dea4e2f1b2d542a9'),
 ('constraint','sla_policies','sla_policies_target_minutes_check','nexo:phase11:contract:sla_policies_target_minutes_check:v2:62acd5b3df939f47805f0dbc847fb8056d73f2c4702f5e713a032b754a0ceb4f'),
 ('constraint','sla_policies','sla_policies_warning_minutes_check','nexo:phase11:contract:sla_policies_warning_minutes_check:v2:ceb51cb63dba4ac5583e5c0df12d16c5349b4ca25e4ab5e6e71156e5b6b5b607'),
 ('constraint','sla_policies','sla_policies_check','nexo:phase11:contract:sla_policies_check:v2:8c2efbdda296dab6effcb6fd1d4bb10e07f818f766f2b95f6062ac76a33ccb4f'),
 ('constraint','development_escalations','development_escalations_status_check','nexo:phase11:contract:development_escalations_status_check:v2:cdd48389db888f5dbfb103be24a2a46d67a63c794744c61aa376563405cc87a4'),
 ('constraint','sla_snapshots','sla_snapshots_clock_type_check','nexo:phase11:contract:sla_snapshots_clock_type_check:v2:806ff6a2762a99899081e356e146e6d94824d7a2f275cd06b8800af253cd2ae4'),
 ('constraint','sla_snapshots','sla_snapshots_clock_mode_check','nexo:phase11:contract:sla_snapshots_clock_mode_check:v2:b97dd8e540a93033e2d41f0a5b901b8c188492d9c8686478756ef5bb36f949fd'),
 ('constraint','sla_clock_segments','sla_clock_segments_check','nexo:phase11:contract:sla_clock_segments_check:v2:c6ca24c24236b9ca6953e5796fa061505c3f8a4c28a1ec295e4e42ff448fe92f'),
 ('index','sla_policies','sla_policies_one_active_idx','nexo:phase11:contract:sla_policies_one_active_idx:v2:4871a14123de8e6c2af8aa69857d5a51482b54c57e735c2aca88866572fea6d3'),
 ('index','development_escalations','development_escalations_active_ticket_idx','nexo:phase11:contract:development_escalations_active_ticket_idx:v2:c628888b2dfab86d5025997a588d7f333a3714976e721196b353dbcbb10501e5'),
 ('index','sla_snapshots','sla_snapshots_support_once_idx','nexo:phase11:contract:sla_snapshots_support_once_idx:v2:df9edd6e9e515a9323270227cd7fdab574bbc9c9e514d0a658e50726df203262'),
 ('index','sla_snapshots','sla_snapshots_escalation_once_idx','nexo:phase11:contract:sla_snapshots_escalation_once_idx:v2:569e5b7cd77a773519ab82587bc8164d5502dde4215d6595d47ddbdb523bc509'),
 ('index','sla_clock_segments','sla_clock_segments_open_idx','nexo:phase11:contract:sla_clock_segments_open_idx:v2:c005e9450a581e2732a7ee439e50a90db27d2e47e830f59f525951356d262833')
 ), expected_functions(signature,result_type,definer) as (values
  ('phase11_calendar_snapshot(bigint)','jsonb',true),('phase11_start_snapshot(bigint,bigint,text,bigint)','bigint',true),('phase11_request_fingerprint(jsonb)','text',true),('phase11_replay(text,text,text,bigint,jsonb)','jsonb',true),('phase11_build_actor_context(text,text,bigint)','bigint',true),('phase11_lock_authorized_ticket(bigint,bigint,text,bigint)','tickets',true),('phase11_validate_transition(text,text,text)','void',false),('phase11_lock_latest_escalation(bigint)','development_escalations',true),('phase11_validate_escalation_transition(tickets,development_escalations,text,bigint)','void',true),('phase11_persist_escalation(bigint,development_escalations,text,text)','development_escalations',true),('phase11_record_escalation_event(development_escalations,jsonb)','bigint',true),('phase11_suspend_ticket_for_development(bigint)','void',true),('phase11_resume_ticket_after_development(bigint)','void',true),('phase11_close_support_clock(bigint,bigint)','void',true),('phase11_close_development_clock(bigint,bigint,text)','void',true),('phase11_resume_support_clock(bigint,bigint)','void',true),('phase11_escalation_response(bigint,bigint,bigint)','jsonb',true),('phase11_transfer_sets_new()','trigger',false),('transition_conversation(jsonb,text,text,text,bigint)','jsonb',true),('claim_conversation(jsonb,text,text,text,bigint)','jsonb',true),('update_development_escalation(jsonb,text,text,text,bigint)','jsonb',true),('configure_sla_policy(bigint,text,text,text,bigint,integer,integer,text)','jsonb',true),('configure_business_calendar(bigint,text,text,jsonb,jsonb,text)','jsonb',true)
), functions as (select e.*,to_regprocedure('public.'||e.signature) oid from expected_functions e),
actor_identity_functions as (
 select e.*,split_part(e.signature,'(',1) in ('transition_conversation','claim_conversation','update_development_escalation') public_rpc
 from functions e where split_part(e.signature,'(',1) in ('phase11_build_actor_context','phase11_lock_authorized_ticket','transition_conversation','claim_conversation','update_development_escalation')
), composite_assignment_functions as (
 select p.proname,p.prosrc from pg_proc p join pg_namespace n on n.oid=p.pronamespace
 where n.nspname='public' and p.oid in (
  to_regprocedure('public.transition_conversation(jsonb,text,text,text,bigint)'),
  to_regprocedure('public.update_development_escalation(jsonb,text,text,text,bigint)'))
),
checks as (
 select 'table_object_types' name,count(*)=0 ok,count(*) violations from tables e left join pg_class c on c.oid=e.oid where c.oid is null or c.relkind<>'r'
 union all select 'complete_column_contract',count(*)=0,count(*) from expected_columns e where not exists(select 1 from pg_attribute a join pg_class t on t.oid=a.attrelid join pg_namespace n on n.oid=t.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname='public' and t.relname=e.table_name and a.attname=e.column_name and not a.attisdropped and format_type(a.atttypid,a.atttypmod)=e.data_type and a.attnotnull<>e.nullable and pg_get_expr(d.adbin,d.adrelid) is not distinct from e.default_expr and a.attidentity=e.identity_kind)
 union all select 'validated_attached_constraint_contract',count(*)=0,count(*) from expected_constraints e where not exists(select 1 from pg_constraint c where c.conrelid=to_regclass('public.'||e.table_name) and c.conname=e.constraint_name and c.convalidated and (c.contype='c' or exists(select 1 from expected_constraint_shapes s where s.table_name=e.table_name and s.constraint_name=e.constraint_name and c.contype=s.constraint_type::"char" and cardinality(c.conkey)=cardinality(s.key_names) and not exists(select 1 from unnest(s.key_names) with ordinality k(name,ord) left join pg_attribute a on a.attrelid=c.conrelid and a.attname=k.name and not a.attisdropped left join unnest(c.conkey) with ordinality actual(attnum,ord) on actual.ord=k.ord where a.attnum is distinct from actual.attnum) and (c.contype<>'f' or (c.confrelid=to_regclass('public.'||s.ref_table) and cardinality(c.confkey)=cardinality(s.ref_key_names) and not exists(select 1 from unnest(s.ref_key_names) with ordinality k(name,ord) left join pg_attribute a on a.attrelid=c.confrelid and a.attname=k.name and not a.attisdropped left join unnest(c.confkey) with ordinality actual(attnum,ord) on actual.ord=k.ord where a.attnum is distinct from actual.attnum) and c.confdeltype=s.delete_action::"char")))) and (c.contype not in ('p','u') or exists(select 1 from pg_index i where i.indexrelid=c.conindid and i.indisvalid and i.indisready)))
 union all select 'new_table_constraint_set_exact',count(*)=0,count(*) from pg_constraint c join tables t on t.oid=c.conrelid where not exists(select 1 from expected_constraints e where e.table_name=t.name and e.constraint_name=c.conname)
 union all select 'valid_index_shape_and_marker_contract',count(*)=0,count(*) from expected_indexes e where not exists(select 1 from pg_index i join pg_class x on x.oid=i.indexrelid join pg_am am on am.oid=x.relam join expected_markers m on m.object_kind='index' and m.table_name=e.table_name and m.object_name=e.index_name where i.indrelid=to_regclass('public.'||e.table_name) and x.relname=e.index_name and am.amname='btree' and i.indisunique=e.is_unique and i.indisvalid and i.indisready and not i.indisprimary and i.indexprs is null and i.indpred is not null and i.indnkeyatts=cardinality(e.key_names) and i.indnatts=i.indnkeyatts and not exists(select 1 from unnest(e.key_names) with ordinality k(name,ord) left join pg_attribute a on a.attrelid=i.indrelid and a.attname=k.name and not a.attisdropped left join unnest(i.indkey) with ordinality actual(attnum,ord) on actual.ord=k.ord where a.attnum is distinct from actual.attnum) and obj_description(x.oid,'pg_class')=m.marker)
 union all select 'check_constraint_marker_contract',count(*)=0,count(*) from expected_markers m where m.object_kind='constraint' and not exists(select 1 from pg_constraint c where c.conrelid=to_regclass('public.'||m.table_name) and c.conname=m.object_name and c.contype='c' and c.convalidated and obj_description(c.oid,'pg_constraint')=m.marker)
 union all select 'function_identity_result_security_path_owner_language',count(*)=0,count(*) from functions e where e.oid is null or not exists(select 1 from pg_proc p join pg_language l on l.oid=p.prolang join pg_roles owner_role on owner_role.oid=p.proowner where p.oid=e.oid and pg_get_function_result(p.oid)=e.result_type and p.prosecdef=e.definer and p.proconfig=array['search_path=pg_catalog, public'] and owner_role.rolname in ('postgres','supabase_admin') and l.lanname=case when split_part(e.signature,'(',1) in ('phase11_calendar_snapshot','phase11_request_fingerprint','phase11_lock_latest_escalation','phase11_suspend_ticket_for_development','phase11_resume_ticket_after_development','phase11_close_support_clock','phase11_close_development_clock','phase11_resume_support_clock','phase11_escalation_response') then 'sql' else 'plpgsql' end and p.provolatile=case when split_part(e.signature,'(',1) in ('phase11_request_fingerprint','phase11_build_actor_context','phase11_validate_transition','phase11_escalation_response') then 'i' when split_part(e.signature,'(',1)='phase11_calendar_snapshot' then 's' else 'v' end)
 union all select 'function_owner_consistency',count(distinct p.proowner)=1,greatest(count(distinct p.proowner)-1,0) from functions e join pg_proc p on p.oid=e.oid
 union all select 'function_overload_set_exact',count(*)=0,count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in (select split_part(signature,'(',1) from expected_functions) and p.oid not in (select oid from functions where oid is not null)
 union all select 'composite_return_assignment_contract',count(*)=0,count(*) from composite_assignment_functions f where f.prosrc~*'select[[:space:]]+public[.]phase11_(lock_authorized_ticket|lock_latest_escalation|persist_escalation)[(][^;]+[)][[:space:]]+into[[:space:]]+v_(ticket|escalation)' or f.prosrc not like '%v_ticket:=public.phase11_lock_authorized_ticket(%' or (f.proname='update_development_escalation' and (f.prosrc not like '%v_escalation:=public.phase11_lock_latest_escalation(%' or f.prosrc not like '%v_escalation:=public.phase11_persist_escalation(%'))
 union all select 'transfer_trigger_exact',count(*)=1,abs(count(*)-1) from pg_trigger t where t.tgrelid=to_regclass('public.tickets') and t.tgname='phase11_transfer_sets_new' and not t.tgisinternal and t.tgenabled='O' and regexp_replace(pg_get_triggerdef(t.oid,true),'[[:space:]]','','g')=regexp_replace('CREATE TRIGGER phase11_transfer_sets_new BEFORE UPDATE OF area_id ON tickets FOR EACH ROW EXECUTE FUNCTION phase11_transfer_sets_new()','[[:space:]]','','g')
 union all select 'rls_enabled',count(*) filter(where c.oid is null or not c.relrowsecurity)=0,count(*) filter(where c.oid is null or not c.relrowsecurity) from tables e left join pg_class c on c.oid=e.oid
 union all select 'service_role_exact_table_acl',count(*) filter(where c.oid is null or not has_table_privilege('service_role',c.oid,'SELECT,INSERT,UPDATE') or has_table_privilege('service_role',c.oid,'DELETE,TRUNCATE,REFERENCES,TRIGGER'))=0,count(*) filter(where c.oid is null or not has_table_privilege('service_role',c.oid,'SELECT,INSERT,UPDATE') or has_table_privilege('service_role',c.oid,'DELETE,TRUNCATE,REFERENCES,TRIGGER')) from tables e left join pg_class c on c.oid=e.oid
 union all select 'service_role_exact_sequence_acl',count(*) filter(where not has_sequence_privilege('service_role',oid,'USAGE,SELECT') or has_sequence_privilege('service_role',oid,'UPDATE'))=0,count(*) filter(where not has_sequence_privilege('service_role',oid,'USAGE,SELECT') or has_sequence_privilege('service_role',oid,'UPDATE')) from sequences
 union all select 'unexpected_effective_relation_grantees',count(*)=0,count(*) from (select c.oid,'r' kind,c.relowner from tables e join pg_class c on c.oid=e.oid union all select oid,'S',relowner from sequences) o cross join pg_roles r where r.rolname not in ('service_role','pg_read_all_data','pg_write_all_data','supabase_etl_admin','supabase_read_only_user') and r.oid<>o.relowner and not r.rolsuper and case when o.kind='S' then has_sequence_privilege(r.oid,o.oid,'USAGE,SELECT,UPDATE') else has_table_privilege(r.oid,o.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') end
 union all select 'public_oid0_relation_denial',count(*)=0,count(*) from (select c.oid,'r' kind,c.relowner from tables e join pg_class c on c.oid=e.oid union all select oid,'S',relowner from sequences) o cross join lateral aclexplode(coalesce((select relacl from pg_class where oid=o.oid),acldefault(o.kind::"char",o.relowner))) a where a.grantee=0
 union all select 'service_role_exact_function_acl',count(*) filter(where oid is null or has_function_privilege('service_role',oid,'EXECUTE')<>(split_part(signature,'(',1) in ('transition_conversation','claim_conversation','update_development_escalation','configure_sla_policy','configure_business_calendar')))=0,count(*) filter(where oid is null or has_function_privilege('service_role',oid,'EXECUTE')<>(split_part(signature,'(',1) in ('transition_conversation','claim_conversation','update_development_escalation','configure_sla_policy','configure_business_calendar'))) from functions
 union all select 'actor_identity_rpc_acl_exact',count(*) filter(where oid is null or has_function_privilege('service_role',oid,'EXECUTE')<>public_rpc)=0,count(*) filter(where oid is null or has_function_privilege('service_role',oid,'EXECUTE')<>public_rpc) from actor_identity_functions
 union all select 'unexpected_effective_function_grantees',count(*)=0,count(*) from functions e join pg_proc p on p.oid=e.oid cross join pg_roles r where r.oid<>p.proowner and not r.rolsuper and r.rolname<>'service_role' and has_function_privilege(r.oid,p.oid,'EXECUTE')
 union all select 'public_oid0_function_denial',count(*)=0,count(*) from functions e join pg_proc p on p.oid=e.oid cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where a.grantee=0 and a.privilege_type='EXECUTE'
)
select name,case when ok then 'PASS' else 'FAIL' end status,violations||' contract violation(s)' detail from checks order by name;
rollback;
